dist: trusty
sudo: false
git:
  depth: 3
language: python
python:
    - "3.7"
before_install:
    - sudo apt-get install -y libhdf5-dev
install:
    - pip install tox flake8
script:
    - flake8 src
    - tox
