#!/usr/bin/env python
import sys
import os

if __name__ == '__main__' and not sys.argv[0]:
    # An example for debugging the new wrapper
    import shutil
    shutil.copy2('/Users/gma/ihme/epi/at_cascade/data/475588/dbs/100/3/dismod.db', '/tmp/t1_diabetes.db')
    sys.argv = 'dmdismod /Users/gma/ihme/epi/at_cascade/data/475643/dbs/100/2/dismod.db ODE init'.split()

if sys.argv[2].upper() == 'ODE':
    """
    # Test commands
    cp -p '/Users/gma/ihme/epi/at_cascade/data/475588/dbs/100/3/dismod.db' '/tmp/t1_diabetes.db'
    dmdismod /tmp/t1_diabetes.db ODE init --subset True --random-seed 1234 --random-subsample 1000 --reference /Users/gma/ihme/epi/at_cascade/t1_diabetes/no_ode/no_ode.db
    dmdismod /tmp/t1_diabetes.db ODE fit --ode-hold-out-list mtexcess --subset True --random-seed 1234 --random-subsample 1000 --reference /Users/gma/ihme/epi/at_cascade/t1_diabetes/yes_ode/yes_ode.db
    dmdismod /tmp/t1_diabetes.db ODE students --ode-hold-out-list mtexcess  --subset True --random-seed 1234 --random-subsample 1000 --reference /Users/gma/ihme/epi/at_cascade/t1_diabetes/students/students.db
    """
    from cascade_at.executor.dmdismod_extensions import dmdismod
    cmd_str = ' '.join(sys.argv)
    print (cmd_str)
    dmdismod(cmd_str)

else:

    cmd_str = ' '.join([k if  ' ' not in k else f"'{k}'" for k in sys.argv[1:]])

    os.system (f"DYLD_LIBRARY_PATH=/opt/prefix/dismod_at/lib64 dismod_at_executable {cmd_str}")

