#!/bin/bash
SINGULARITY=/ihme/singularity-images/dismod/current.img
INSTALLED_DISMOD=$(which dismod_at 2>/dev/null)
if [ -e "${SINGULARITY}" ]
then
    exec singularity exec "${SINGULARITY}" /home/root/prefix/dismod_at/bin/dismod_at $*
elif [ -x "${INSTALLED_DISMOD}" ]
then
    dismod_at $*
else
    TARGET_DIR="$( cd "$(dirname $1)" ; pwd -P )"
    TARGET_DB=$(basename $1)
    shift
    if [[ $- == *i* ]]; then
        INTERACTIVE="-it"
    else
        INTERACTIVE=""
    fi
    exec docker run $INTERACTIVE --mount type=bind,source=${TARGET_DIR},target=/app reg.ihme.washington.edu/dismod/dismod_at /home/root/prefix/dismod_at/bin/dismod_at /app/$TARGET_DB $*
fi
