#!/bin/bash
SINGULARITY=/ihme/singularity-images/dismod/current.img
if [ -e "${SINGULARITY}" ]
then
    exec singularity exec "${SINGULARITY}" /home/root/prefix/dismod_at/bin/dismodat.py $*
else
    CURDIR=$(pwd)
    exec docker run reg.ihme.washington.edu/dismod/dismod_at -it  --mount type=bind,source=${CURDIR},target=/app  /home/root/prefix/dismod_at/bin/dismodat.py $*
fi
