#!/bin/bash
SINGULARITY=/ihme/singularity-images/mscm/current.img
if [ -e "${SINGULARITY}" ]
then
    export LD_LIBRARY_PATH="/home/prefix/dismod_at.release/lib64:${LD_LIBRARY_PATH}"
    exec singularity exec "${SINGULARITY}" /home/prefix/dismod_at/bin/dismodat.py $*
else
    CURDIR=$(pwd)
    exec docker run -it --mount type=bind,source=${CURDIR},target=/app reg.ihme.washington.edu/mscm/dismod_at /home/prefix/dismod_at/bin/dismodat.py $*
fi
